// Central registry of every governed mutating action: the single source
// of truth for each action key's entity type and destructive/risk posture,
// consumed by ensureMutationAllowed() (server/middleware/governance.js) as
// the default when a route does not explicitly override it, and enforced
// against every ensureMutationAllowed() call site in server/routes/*.js by
// tests/unit/server/governance-coverage.test.js (fails CI on a new action
// key with no catalog entry, or on a destructive-flag mismatch between a
// route and its catalog entry).
const ACTIONS = {
  alert_bulk_state_save: { entityType: 'alert-batch', destructive: false, risk: 'low' },
  alert_policy_delete: { entityType: 'alert-policy', destructive: true, risk: 'high' },
  alert_policy_save: { entityType: 'alert-policy', destructive: false, risk: 'low' },
  alert_state_save: { entityType: 'alert', destructive: false, risk: 'low' },
  compose_deploy: { entityType: 'compose', destructive: false, risk: 'low' },
  connection_create: { entityType: 'connection', destructive: false, risk: 'low' },
  connection_default: { entityType: 'connection', destructive: false, risk: 'low' },
  connection_delete: { entityType: 'connection', destructive: true, risk: 'high' },
  connection_update: { entityType: 'connection', destructive: false, risk: 'low' },
  credential_create: { entityType: 'credential', destructive: false, risk: 'low' },
  credential_delete: { entityType: 'credential', destructive: true, risk: 'high' },
  credential_update: { entityType: 'credential', destructive: false, risk: 'low' },
  host_config_update: { entityType: 'host', destructive: false, risk: 'low' },
  host_maintenance_enter: { entityType: 'host', destructive: false, risk: 'low' },
  host_maintenance_exit: { entityType: 'host', destructive: false, risk: 'low' },
  host_multipathing_update: { entityType: 'host', destructive: true, risk: 'high' },
  host_reboot: { entityType: 'host', destructive: true, risk: 'high' },
  host_shutdown: { entityType: 'host', destructive: true, risk: 'high' },
  host_target_create: { entityType: 'host-target', destructive: false, risk: 'low' },
  host_target_delete: { entityType: 'host-target', destructive: true, risk: 'high' },
  host_target_update: { entityType: 'host-target', destructive: false, risk: 'low' },
  inventory_workspace_delete: { entityType: 'workspace', destructive: true, risk: 'high' },
  inventory_workspace_save: { entityType: 'workspace', destructive: false, risk: 'low' },
  lifecycle_plan_delete: { entityType: 'host', destructive: true, risk: 'high' },
  lifecycle_plan_save: { entityType: 'host', destructive: false, risk: 'low' },
  log_export: { entityType: 'log-export', destructive: false, risk: 'low' },
  managed_target_register: { entityType: 'managed-target', destructive: false, risk: 'low' },
  managed_target_update: { entityType: 'managed-target', destructive: false, risk: 'low' },
  network_bond_create: { entityType: 'network', destructive: false, risk: 'low' },
  network_config_update: { entityType: 'network', destructive: false, risk: 'low' },
  network_create: { entityType: 'network', destructive: false, risk: 'low' },
  network_destroy: { entityType: 'network', destructive: true, risk: 'high' },
  network_vif_config_update: { entityType: 'vif', destructive: false, risk: 'low' },
  network_vlan_create: { entityType: 'network', destructive: false, risk: 'low' },
  organization_create: { entityType: 'organization', destructive: false, risk: 'low' },
  organization_delete: { entityType: 'organization', destructive: true, risk: 'high' },
  pool_config_update: { entityType: 'pool', destructive: false, risk: 'low' },
  pool_ha_update: { entityType: 'pool', destructive: false, risk: 'low' },
  pool_host_eject: { entityType: 'host', destructive: true, risk: 'high' },
  pool_join: { entityType: 'host', destructive: true, risk: 'high' },
  project_create: { entityType: 'project', destructive: false, risk: 'low' },
  project_delete: { entityType: 'project', destructive: true, risk: 'high' },
  project_member_save: { entityType: 'project', destructive: false, risk: 'low' },
  project_quota_save: { entityType: 'project', destructive: false, risk: 'low' },
  project_update: { entityType: 'project', destructive: false, risk: 'low' },
  remediation_task_create: { entityType: 'task', destructive: false, risk: 'low' },
  remediation_task_update: { entityType: 'task', destructive: false, risk: 'low' },
  remediation_template_delete: { entityType: 'task-template', destructive: true, risk: 'high' },
  remediation_template_save: { entityType: 'task-template', destructive: false, risk: 'low' },
  resilience_drill_log: { entityType: 'pool', destructive: false, risk: 'low' },
  resilience_runbook_delete: { entityType: 'pool', destructive: true, risk: 'high' },
  resilience_runbook_save: { entityType: 'pool', destructive: false, risk: 'low' },
  retention_policy_save: { entityType: 'retention-domain', destructive: false, risk: 'low' },
  retention_sweep_preview: { entityType: 'retention-domain', destructive: false, risk: 'low' },
  retention_sweep_run: { entityType: 'retention-domain', destructive: true, risk: 'high' },
  sr_config_update: { entityType: 'sr', destructive: false, risk: 'low' },
  sr_create: { entityType: 'host', destructive: false, risk: 'low' },
  sr_destroy: { entityType: 'sr', destructive: true, risk: 'high' },
  sr_file_delete: { entityType: 'sr', destructive: true, risk: 'high' },
  sr_file_mkdir: { entityType: 'sr', destructive: false, risk: 'low' },
  sr_file_move: { entityType: 'sr', destructive: false, risk: 'low' },
  sr_file_upload: { entityType: 'sr', destructive: false, risk: 'low' },
  sr_forget: { entityType: 'sr', destructive: true, risk: 'high' },
  sr_import: { entityType: 'host', destructive: false, risk: 'low' },
  sr_local_cache_update: { entityType: 'sr', destructive: false, risk: 'low' },
  sr_repair: { entityType: 'sr', destructive: false, risk: 'low' },
  sr_rescan: { entityType: 'sr', destructive: false, risk: 'low' },
  sr_vdi_create: { entityType: 'sr', destructive: false, risk: 'low' },
  system_config_save: { entityType: 'settings-section', destructive: false, risk: 'low' },
  template_create: { entityType: 'template', destructive: false, risk: 'low' },
  template_deploy: { entityType: 'template', destructive: false, risk: 'low' },
  template_deployment_validate: { entityType: 'vm', destructive: false, risk: 'low' },
  template_governance_restore: { entityType: 'template', destructive: false, risk: 'low' },
  template_governance_save: { entityType: 'template', destructive: false, risk: 'low' },
  template_library_folder_create: { entityType: 'template-library-folder', destructive: false, risk: 'low' },
  template_library_folder_delete: { entityType: 'template-library-folder', destructive: true, risk: 'high' },
  template_library_folder_move: { entityType: 'template-library-folder', destructive: false, risk: 'low' },
  template_library_folder_rename: { entityType: 'template-library-folder', destructive: false, risk: 'low' },
  template_library_item_create: { entityType: 'template-library-item', destructive: false, risk: 'low' },
  template_library_item_delete: { entityType: 'template-library-item', destructive: true, risk: 'high' },
  template_library_item_move: { entityType: 'template-library-item', destructive: false, risk: 'low' },
  template_library_item_rename: { entityType: 'template-library-item', destructive: false, risk: 'low' },
  template_library_item_save: { entityType: 'template-library-item', destructive: false, risk: 'low' },
  template_promote: { entityType: 'template', destructive: false, risk: 'low' },
  vault_rewrap: { entityType: 'vault', destructive: false, risk: 'low' },
  vdi_attach_cd: { entityType: 'vdi', destructive: false, risk: 'low' },
  vdi_clone: { entityType: 'vdi', destructive: false, risk: 'low' },
  vdi_delete: { entityType: 'vdi', destructive: true, risk: 'high' },
  vdi_resize: { entityType: 'vdi', destructive: false, risk: 'low' },
  vdi_snapshot: { entityType: 'vdi', destructive: false, risk: 'low' },
  vfabric_create: { entityType: 'vfabric', destructive: false, risk: 'low' },
  vfabric_delete: { entityType: 'vfabric', destructive: true, risk: 'high' },
  vfabric_quota_delete: { entityType: 'vfabric', destructive: true, risk: 'high' },
  vfabric_quota_save: { entityType: 'vfabric', destructive: false, risk: 'low' },
  vfabric_update: { entityType: 'vfabric', destructive: false, risk: 'low' },
  vm_config_update: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_create: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_disk_add: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_duplicate_create: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_import: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_migrate: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_nic_add: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_nic_disconnect: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_nic_remove: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_reboot: { entityType: 'vm', destructive: true, risk: 'high' },
  vm_resume: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_shutdown: { entityType: 'vm', destructive: true, risk: 'high' },
  vm_snapshot_create: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_snapshot_delete: { entityType: 'vm-snapshot', destructive: true, risk: 'high' },
  vm_snapshot_revert: { entityType: 'vm-snapshot', destructive: true, risk: 'high' },
  vm_start: { entityType: 'vm', destructive: false, risk: 'low' },
  vm_suspend: { entityType: 'vm', destructive: true, risk: 'high' },
  workflow_approve: { entityType: 'workflow', destructive: false, risk: 'low' },
  workflow_cancel: { entityType: 'workflow', destructive: false, risk: 'low' },
  workflow_create: { entityType: 'workflow', destructive: false, risk: 'low' },
};

function get(actionKey) {
  return ACTIONS[actionKey] || null;
}

module.exports = { ACTIONS, get };
